version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 127.0.0.1:8009:3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
  pg:
    image: postgres:latest
    env_file:
      - .env
