departments = Department.create([
  {name: "Antioquia", cod_department: 5},
  {name: "Norte de Santander", cod_department: 54},
  {name: "Meta", cod_department: 50},
  {name: "Chocó", cod_department: 27},
  {name: "Huila", cod_department: 41},
  {name: "Bolívar", cod_department: 13},
  {name: "Cundinamarca", cod_department: 25},
  {name: "Cesar", cod_department: 20},
  {name: "Santander", cod_department: 68},
  {name: "Caldas", cod_department: 17},
  {name: "Casanare", cod_department: 85},
  {name: "Nariño", cod_department: 52},
  {name: "Caquetá", cod_department: 18},
  {name: "La Guajira", cod_department: 44},
  {name: "Valle del Cauca", cod_department: 76},
  {name: "Magdalena", cod_department: 47},
  {name: "Cauca", cod_department: 19},
  {name: "Boyacá", cod_department: 15},
  {name: "Tolima", cod_department: 73},
  {name: "Risaralda", cod_department: 66},
  {name: "Arauca", cod_department: 81},
  {name: "Quindío", cod_department: 63},
  {name: "Córdoba", cod_department: 23},
  {name: "Atlántico", cod_department: 8},
  {name: "Guainía", cod_department: 94},
  {name: "Bogotá D.C.", cod_department: 11},
  {name: "Sucre", cod_department: 70},
  {name: "Guaviare", cod_department: 95},
  {name: "Vaupés", cod_department: 97},
  {name: "Putumayo", cod_department: 86},
  {name: "Vichada", cod_department: 99},
  {name: "Amazonas", cod_department: 91},
  {name: "Archipiélago de San Andrés, Providencia y Santa Catalina", cod_department: 88},
  {name: "Consulado", cod_department: 999}
  ])

municipalities = [
  {name: "Abejorral", cod_department: 5, cod_monicipality: 5002},
  {name: "Abrego", cod_department: 54, cod_monicipality: 54003},
  {name: "Abriaquí", cod_department: 5, cod_monicipality: 5004},
  {name: "Acacias", cod_department: 50, cod_monicipality: 50006},
  {name: "Acandí", cod_department: 27, cod_monicipality: 27006},
  {name: "Acevedo", cod_department: 41, cod_monicipality: 41006},
  {name: "Achí", cod_department: 13, cod_monicipality: 13006},
  {name: "Agrado", cod_department: 41, cod_monicipality: 41013},
  {name: "Agua de Dios", cod_department: 25, cod_monicipality: 25001},
  {name: "Aguachica", cod_department: 20, cod_monicipality: 20011},
  {name: "Aguada", cod_department: 68, cod_monicipality: 68013},
  {name: "Aguadas", cod_department: 17, cod_monicipality: 17013},
  {name: "Aguazul", cod_department: 85, cod_monicipality: 85010},
  {name: "Agustín Codazzi", cod_department: 20, cod_monicipality: 20013},
  {name: "Aipe", cod_department: 41, cod_monicipality: 41016},
  {name: "Albán", cod_department: 25, cod_monicipality: 25019},
  {name: "Albán", cod_department: 52, cod_monicipality: 52019},
  {name: "Albania", cod_department: 18, cod_monicipality: 18029},
  {name: "Albania", cod_department: 44, cod_monicipality: 44035},
  {name: "Albania", cod_department: 68, cod_monicipality: 68020},
  {name: "Alcalá", cod_department: 76, cod_monicipality: 76020},
  {name: "Aldana", cod_department: 52, cod_monicipality: 52022},
  {name: "Alejandría", cod_department: 5, cod_monicipality: 5021},
  {name: "Algarrobo", cod_department: 47, cod_monicipality: 47030},
  {name: "Algeciras", cod_department: 41, cod_monicipality: 41020},
  {name: "Almaguer", cod_department: 19, cod_monicipality: 19022},
  {name: "Almeida", cod_department: 15, cod_monicipality: 15022},
  {name: "Alpujarra", cod_department: 73, cod_monicipality: 73024},
  {name: "Altamira", cod_department: 41, cod_monicipality: 41026},
  {name: "Alto Baudo", cod_department: 27, cod_monicipality: 27025},
  {name: "Altos del Rosario", cod_department: 13, cod_monicipality: 13030},
  {name: "Alvarado", cod_department: 73, cod_monicipality: 73026},
  {name: "Amagá", cod_department: 5, cod_monicipality: 5030},
  {name: "Amalfi", cod_department: 5, cod_monicipality: 5031},
  {name: "Ambalema", cod_department: 73, cod_monicipality: 73030},
  {name: "Anapoima", cod_department: 25, cod_monicipality: 25035},
  {name: "Ancuyá", cod_department: 52, cod_monicipality: 52036},
  {name: "Andalucía", cod_department: 76, cod_monicipality: 76036},
  {name: "Andes", cod_department: 5, cod_monicipality: 5034},
  {name: "Angelópolis", cod_department: 5, cod_monicipality: 5036},
  {name: "Angostura", cod_department: 5, cod_monicipality: 5038},
  {name: "Anolaima", cod_department: 25, cod_monicipality: 25040},
  {name: "Anorí", cod_department: 5, cod_monicipality: 5040},
  {name: "Anserma", cod_department: 17, cod_monicipality: 17042},
  {name: "Ansermanuevo", cod_department: 76, cod_monicipality: 76041},
  {name: "Anza", cod_department: 5, cod_monicipality: 5044},
  {name: "Anzoátegui", cod_department: 73, cod_monicipality: 73043},
  {name: "Apartadó", cod_department: 5, cod_monicipality: 5045},
  {name: "Apía", cod_department: 66, cod_monicipality: 66045},
  {name: "Apulo", cod_department: 25, cod_monicipality: 25599},
  {name: "Aquitania", cod_department: 15, cod_monicipality: 15047},
  {name: "Aracataca", cod_department: 47, cod_monicipality: 47053},
  {name: "Aranzazu", cod_department: 17, cod_monicipality: 17050},
  {name: "Aratoca", cod_department: 68, cod_monicipality: 68051},
  {name: "Arauca", cod_department: 81, cod_monicipality: 81001},
  {name: "Arauquita", cod_department: 81, cod_monicipality: 81065},
  {name: "Arbeláez", cod_department: 25, cod_monicipality: 25053},
  {name: "Arboleda", cod_department: 52, cod_monicipality: 52051},
  {name: "Arboledas", cod_department: 54, cod_monicipality: 54051},
  {name: "Arboletes", cod_department: 5, cod_monicipality: 5051},
  {name: "Arcabuco", cod_department: 15, cod_monicipality: 15051},
  {name: "Arenal", cod_department: 13, cod_monicipality: 13042},
  {name: "Argelia", cod_department: 5, cod_monicipality: 5055},
  {name: "Argelia", cod_department: 19, cod_monicipality: 19050},
  {name: "Argelia", cod_department: 76, cod_monicipality: 76054},
  {name: "Ariguaní", cod_department: 47, cod_monicipality: 47058},
  {name: "Arjona", cod_department: 13, cod_monicipality: 13052},
  {name: "Armenia", cod_department: 5, cod_monicipality: 5059},
  {name: "Armenia", cod_department: 63, cod_monicipality: 63001},
  {name: "Armero", cod_department: 73, cod_monicipality: 73055},
  {name: "Arroyohondo", cod_department: 13, cod_monicipality: 13062},
  {name: "Astrea", cod_department: 20, cod_monicipality: 20032},
  {name: "Ataco", cod_department: 73, cod_monicipality: 73067},
  {name: "Atrato", cod_department: 27, cod_monicipality: 27050},
  {name: "Ayapel", cod_department: 23, cod_monicipality: 23068},
  {name: "Bagadó", cod_department: 27, cod_monicipality: 27073},
  {name: "Bahía Solano", cod_department: 27, cod_monicipality: 27075},
  {name: "Bajo Baudó", cod_department: 27, cod_monicipality: 27077},
  {name: "Balboa", cod_department: 19, cod_monicipality: 19075},
  {name: "Balboa", cod_department: 66, cod_monicipality: 66075},
  {name: "Baranoa", cod_department: 8, cod_monicipality: 8078},
  {name: "Baraya", cod_department: 41, cod_monicipality: 41078},
  {name: "Barbacoas", cod_department: 52, cod_monicipality: 52079},
  {name: "Barbosa", cod_department: 5, cod_monicipality: 5079},
  {name: "Barbosa", cod_department: 68, cod_monicipality: 68077},
  {name: "Barichara", cod_department: 68, cod_monicipality: 68079},
  {name: "Barranca de Upía", cod_department: 50, cod_monicipality: 50110},
  {name: "Barrancabermeja", cod_department: 68, cod_monicipality: 68081},
  {name: "Barrancas", cod_department: 44, cod_monicipality: 44078},
  {name: "Barranco de Loba", cod_department: 13, cod_monicipality: 13074},
  {name: "Barranco Minas", cod_department: 94, cod_monicipality: 94343},
  {name: "Barranquilla", cod_department: 8, cod_monicipality: 8001},
  {name: "Becerril", cod_department: 20, cod_monicipality: 20045},
  {name: "Belalcázar", cod_department: 17, cod_monicipality: 17088},
  {name: "Belén", cod_department: 15, cod_monicipality: 15087},
  {name: "Belén", cod_department: 52, cod_monicipality: 52083},
  {name: "Belén de Bajira", cod_department: 27, cod_monicipality: 27086},
  {name: "Belén de Los Andaquies", cod_department: 18, cod_monicipality: 18094},
  {name: "Belén de Umbría", cod_department: 66, cod_monicipality: 66088},
  {name: "Bello", cod_department: 5, cod_monicipality: 5088},
  {name: "Belmira", cod_department: 5, cod_monicipality: 5086},
  {name: "Beltrán", cod_department: 25, cod_monicipality: 25086},
  {name: "Berbeo", cod_department: 15, cod_monicipality: 15090},
  {name: "Betania", cod_department: 5, cod_monicipality: 5091},
  {name: "Betéitiva", cod_department: 15, cod_monicipality: 15092},
  {name: "Betulia", cod_department: 5, cod_monicipality: 5093},
  {name: "Betulia", cod_department: 68, cod_monicipality: 68092},
  {name: "Bituima", cod_department: 25, cod_monicipality: 25095},
  {name: "Boavita", cod_department: 15, cod_monicipality: 15097},
  {name: "Bochalema", cod_department: 54, cod_monicipality: 54099},
  {name: "Bogotá D.C.", cod_department: 11, cod_monicipality: 11001},
  {name: "Bojacá", cod_department: 25, cod_monicipality: 25099},
  {name: "Bojaya", cod_department: 27, cod_monicipality: 27099},
  {name: "Bolívar", cod_department: 19, cod_monicipality: 19100},
  {name: "Bolívar", cod_department: 68, cod_monicipality: 68101},
  {name: "Bolívar", cod_department: 76, cod_monicipality: 76100},
  {name: "Bosconia", cod_department: 20, cod_monicipality: 20060},
  {name: "Boyacá", cod_department: 15, cod_monicipality: 15104},
  {name: "Briceño", cod_department: 5, cod_monicipality: 5107},
  {name: "Briceño", cod_department: 15, cod_monicipality: 15106},
  {name: "Bucaramanga", cod_department: 68, cod_monicipality: 68001},
  {name: "Bucarasica", cod_department: 54, cod_monicipality: 54109},
  {name: "Buena Vista", cod_department: 15, cod_monicipality: 15109},
  {name: "Buenaventura", cod_department: 76, cod_monicipality: 76109},
  {name: "Buenavista", cod_department: 23, cod_monicipality: 23079},
  {name: "Buenavista", cod_department: 63, cod_monicipality: 63111},
  {name: "Buenavista", cod_department: 70, cod_monicipality: 70110},
  {name: "Buenos Aires", cod_department: 19, cod_monicipality: 19110},
  {name: "Buesaco", cod_department: 52, cod_monicipality: 52110},
  {name: "Bugalagrande", cod_department: 76, cod_monicipality: 76113},
  {name: "Buriticá", cod_department: 5, cod_monicipality: 5113},
  {name: "Busbanzá", cod_department: 15, cod_monicipality: 15114},
  {name: "Cabrera", cod_department: 25, cod_monicipality: 25120},
  {name: "Cabrera", cod_department: 68, cod_monicipality: 68121},
  {name: "Cabuyaro", cod_department: 50, cod_monicipality: 50124},
  {name: "Cacahual", cod_department: 94, cod_monicipality: 94886},
  {name: "Cáceres", cod_department: 5, cod_monicipality: 5120},
  {name: "Cachipay", cod_department: 25, cod_monicipality: 25123},
  {name: "Cachirá", cod_department: 54, cod_monicipality: 54128},
  {name: "Cácota", cod_department: 54, cod_monicipality: 54125},
  {name: "Caicedo", cod_department: 5, cod_monicipality: 5125},
  {name: "Caicedonia", cod_department: 76, cod_monicipality: 76122},
  {name: "Caimito", cod_department: 70, cod_monicipality: 70124},
  {name: "Cajamarca", cod_department: 73, cod_monicipality: 73124},
  {name: "Cajibío", cod_department: 19, cod_monicipality: 19130},
  {name: "Cajicá", cod_department: 25, cod_monicipality: 25126},
  {name: "Calamar", cod_department: 13, cod_monicipality: 13140},
  {name: "Calamar", cod_department: 95, cod_monicipality: 95015},
  {name: "Calarcá", cod_department: 63, cod_monicipality: 63130},
  {name: "Caldas", cod_department: 5, cod_monicipality: 5129},
  {name: "Caldas", cod_department: 15, cod_monicipality: 15131},
  {name: "Caldono", cod_department: 19, cod_monicipality: 19137},
  {name: "Cali", cod_department: 76, cod_monicipality: 76001},
  {name: "California", cod_department: 68, cod_monicipality: 68132},
  {name: "Calima", cod_department: 76, cod_monicipality: 76126},
  {name: "Caloto", cod_department: 19, cod_monicipality: 19142},
  {name: "Campamento", cod_department: 5, cod_monicipality: 5134},
  {name: "Campo de La Cruz", cod_department: 8, cod_monicipality: 8137},
  {name: "Campoalegre", cod_department: 41, cod_monicipality: 41132},
  {name: "Campohermoso", cod_department: 15, cod_monicipality: 15135},
  {name: "Canalete", cod_department: 23, cod_monicipality: 23090},
  {name: "Candelaria", cod_department: 8, cod_monicipality: 8141},
  {name: "Candelaria", cod_department: 76, cod_monicipality: 76130},
  {name: "Cantagallo", cod_department: 13, cod_monicipality: 13160},
  {name: "Cañasgordas", cod_department: 5, cod_monicipality: 5138},
  {name: "Caparrapí", cod_department: 25, cod_monicipality: 25148},
  {name: "Capitanejo", cod_department: 68, cod_monicipality: 68147},
  {name: "Caqueza", cod_department: 25, cod_monicipality: 25151},
  {name: "Caracolí", cod_department: 5, cod_monicipality: 5142},
  {name: "Caramanta", cod_department: 5, cod_monicipality: 5145},
  {name: "Carcasí", cod_department: 68, cod_monicipality: 68152},
  {name: "Carepa", cod_department: 5, cod_monicipality: 5147},
  {name: "Carmen de Apicala", cod_department: 73, cod_monicipality: 73148},
  {name: "Carmen de Carupa", cod_department: 25, cod_monicipality: 25154},
  {name: "Carmen del Darien", cod_department: 27, cod_monicipality: 27150},
  {name: "Carolina", cod_department: 5, cod_monicipality: 5150},
  {name: "Cartagena", cod_department: 13, cod_monicipality: 13001},
  {name: "Cartagena del Chairá", cod_department: 18, cod_monicipality: 18150},
  {name: "Cartago", cod_department: 76, cod_monicipality: 76147},
  {name: "Caruru", cod_department: 97, cod_monicipality: 97161},
  {name: "Casabianca", cod_department: 73, cod_monicipality: 73152},
  {name: "Castilla la Nueva", cod_department: 50, cod_monicipality: 50150},
  {name: "Caucasia", cod_department: 5, cod_monicipality: 5154},
  {name: "Cepitá", cod_department: 68, cod_monicipality: 68160},
  {name: "Cereté", cod_department: 23, cod_monicipality: 23162},
  {name: "Cerinza", cod_department: 15, cod_monicipality: 15162},
  {name: "Cerrito", cod_department: 68, cod_monicipality: 68162},
  {name: "Cerro San Antonio", cod_department: 47, cod_monicipality: 47161},
  {name: "Cértegui", cod_department: 27, cod_monicipality: 27160},
  {name: "Chachagüí", cod_department: 52, cod_monicipality: 52240},
  {name: "Chaguaní", cod_department: 25, cod_monicipality: 25168},
  {name: "Chalán", cod_department: 70, cod_monicipality: 70230},
  {name: "Chámeza", cod_department: 85, cod_monicipality: 85015},
  {name: "Chaparral", cod_department: 73, cod_monicipality: 73168},
  {name: "Charalá", cod_department: 68, cod_monicipality: 68167},
  {name: "Charta", cod_department: 68, cod_monicipality: 68169},
  {name: "Chía", cod_department: 25, cod_monicipality: 25175},
  {name: "Chigorodó", cod_department: 5, cod_monicipality: 5172},
  {name: "Chimá", cod_department: 23, cod_monicipality: 23168},
  {name: "Chimá", cod_department: 68, cod_monicipality: 68176},
  {name: "Chimichagua", cod_department: 20, cod_monicipality: 20175},
  {name: "Chinácota", cod_department: 54, cod_monicipality: 54172},
  {name: "Chinavita", cod_department: 15, cod_monicipality: 15172},
  {name: "Chinchiná", cod_department: 17, cod_monicipality: 17174},
  {name: "Chinú", cod_department: 23, cod_monicipality: 23182},
  {name: "Chipaque", cod_department: 25, cod_monicipality: 25178},
  {name: "Chipatá", cod_department: 68, cod_monicipality: 68179},
  {name: "Chiquinquirá", cod_department: 15, cod_monicipality: 15176},
  {name: "Chíquiza", cod_department: 15, cod_monicipality: 15232},
  {name: "Chiriguaná", cod_department: 20, cod_monicipality: 20178},
  {name: "Chiscas", cod_department: 15, cod_monicipality: 15180},
  {name: "Chita", cod_department: 15, cod_monicipality: 15183},
  {name: "Chitagá", cod_department: 54, cod_monicipality: 54174},
  {name: "Chitaraque", cod_department: 15, cod_monicipality: 15185},
  {name: "Chivatá", cod_department: 15, cod_monicipality: 15187},
  {name: "Chivolo", cod_department: 47, cod_monicipality: 47170},
  {name: "Chivor", cod_department: 15, cod_monicipality: 15236},
  {name: "Choachí", cod_department: 25, cod_monicipality: 25181},
  {name: "Chocontá", cod_department: 25, cod_monicipality: 25183},
  {name: "Cicuco", cod_department: 13, cod_monicipality: 13188},
  {name: "Ciénaga", cod_department: 47, cod_monicipality: 47189},
  {name: "Ciénaga de Oro", cod_department: 23, cod_monicipality: 23189},
  {name: "Ciénega", cod_department: 15, cod_monicipality: 15189},
  {name: "Cimitarra", cod_department: 68, cod_monicipality: 68190},
  {name: "Circasia", cod_department: 63, cod_monicipality: 63190},
  {name: "Cisneros", cod_department: 5, cod_monicipality: 5190},
  {name: "Ciudad Bolívar", cod_department: 5, cod_monicipality: 5101},
  {name: "Clemencia", cod_department: 13, cod_monicipality: 13222},
  {name: "Cocorná", cod_department: 5, cod_monicipality: 5197},
  {name: "Coello", cod_department: 73, cod_monicipality: 73200},
  {name: "Cogua", cod_department: 25, cod_monicipality: 25200},
  {name: "Colombia", cod_department: 41, cod_monicipality: 41206},
  {name: "Colón", cod_department: 52, cod_monicipality: 52203},
  {name: "Colón", cod_department: 86, cod_monicipality: 86219},
  {name: "Coloso", cod_department: 70, cod_monicipality: 70204},
  {name: "Cómbita", cod_department: 15, cod_monicipality: 15204},
  {name: "Concepción", cod_department: 5, cod_monicipality: 5206},
  {name: "Concepción", cod_department: 68, cod_monicipality: 68207},
  {name: "Concordia", cod_department: 5, cod_monicipality: 5209},
  {name: "Concordia", cod_department: 47, cod_monicipality: 47205},
  {name: "Condoto", cod_department: 27, cod_monicipality: 27205},
  {name: "Confines", cod_department: 68, cod_monicipality: 68209},
  {name: "Consaca", cod_department: 52, cod_monicipality: 52207},
  {name: "Contadero", cod_department: 52, cod_monicipality: 52210},
  {name: "Contratación", cod_department: 68, cod_monicipality: 68211},
  {name: "Convención", cod_department: 54, cod_monicipality: 54206},
  {name: "Copacabana", cod_department: 5, cod_monicipality: 5212},
  {name: "Coper", cod_department: 15, cod_monicipality: 15212},
  {name: "Córdoba", cod_department: 13, cod_monicipality: 13212},
  {name: "Córdoba", cod_department: 52, cod_monicipality: 52215},
  {name: "Córdoba", cod_department: 63, cod_monicipality: 63212},
  {name: "Corinto", cod_department: 19, cod_monicipality: 19212},
  {name: "Coromoro", cod_department: 68, cod_monicipality: 68217},
  {name: "Corozal", cod_department: 70, cod_monicipality: 70215},
  {name: "Corrales", cod_department: 15, cod_monicipality: 15215},
  {name: "Cota", cod_department: 25, cod_monicipality: 25214},
  {name: "Cotorra", cod_department: 23, cod_monicipality: 23300},
  {name: "Covarachía", cod_department: 15, cod_monicipality: 15218},
  {name: "Coveñas", cod_department: 70, cod_monicipality: 70221},
  {name: "Coyaima", cod_department: 73, cod_monicipality: 73217},
  {name: "Cravo Norte", cod_department: 81, cod_monicipality: 81220},
  {name: "Cuaspud", cod_department: 52, cod_monicipality: 52224},
  {name: "Cubará", cod_department: 15, cod_monicipality: 15223},
  {name: "Cubarral", cod_department: 50, cod_monicipality: 50223},
  {name: "Cucaita", cod_department: 15, cod_monicipality: 15224},
  {name: "Cucunubá", cod_department: 25, cod_monicipality: 25224},
  {name: "Cúcuta", cod_department: 54, cod_monicipality: 54001},
  {name: "Cucutilla", cod_department: 54, cod_monicipality: 54223},
  {name: "Cuítiva", cod_department: 15, cod_monicipality: 15226},
  {name: "Cumaral", cod_department: 50, cod_monicipality: 50226},
  {name: "Cumaribo", cod_department: 99, cod_monicipality: 99773},
  {name: "Cumbal", cod_department: 52, cod_monicipality: 52227},
  {name: "Cumbitara", cod_department: 52, cod_monicipality: 52233},
  {name: "Cunday", cod_department: 73, cod_monicipality: 73226},
  {name: "Curillo", cod_department: 18, cod_monicipality: 18205},
  {name: "Curití", cod_department: 68, cod_monicipality: 68229},
  {name: "Curumaní", cod_department: 20, cod_monicipality: 20228},
  {name: "Dabeiba", cod_department: 5, cod_monicipality: 5234},
  {name: "Dagua", cod_department: 76, cod_monicipality: 76233},
  {name: "Dibula", cod_department: 44, cod_monicipality: 44090},
  {name: "Distracción", cod_department: 44, cod_monicipality: 44098},
  {name: "Dolores", cod_department: 73, cod_monicipality: 73236},
  {name: "Don Matías", cod_department: 5, cod_monicipality: 5237},
  {name: "Dosquebradas", cod_department: 66, cod_monicipality: 66170},
  {name: "Duitama", cod_department: 15, cod_monicipality: 15238},
  {name: "Durania", cod_department: 54, cod_monicipality: 54239},
  {name: "Ebéjico", cod_department: 5, cod_monicipality: 5240},
  {name: "El Águila", cod_department: 76, cod_monicipality: 76243},
  {name: "El Bagre", cod_department: 5, cod_monicipality: 5250},
  {name: "El Banco", cod_department: 47, cod_monicipality: 47245},
  {name: "El Cairo", cod_department: 76, cod_monicipality: 76246},
  {name: "El Calvario", cod_department: 50, cod_monicipality: 50245},
  {name: "El Cantón del San Pablo", cod_department: 27, cod_monicipality: 27135},
  {name: "El Carmen", cod_department: 54, cod_monicipality: 54245},
  {name: "El Carmen de Atrato", cod_department: 27, cod_monicipality: 27245},
  {name: "El Carmen de Bolívar", cod_department: 13, cod_monicipality: 13244},
  {name: "El Carmen de Chucurí", cod_department: 68, cod_monicipality: 68235},
  {name: "El Carmen de Viboral", cod_department: 5, cod_monicipality: 5148},
  {name: "El Castillo", cod_department: 50, cod_monicipality: 50251},
  {name: "El Cerrito", cod_department: 76, cod_monicipality: 76248},
  {name: "El Charco", cod_department: 52, cod_monicipality: 52250},
  {name: "El Cocuy", cod_department: 15, cod_monicipality: 15244},
  {name: "El Colegio", cod_department: 25, cod_monicipality: 25245},
  {name: "El Copey", cod_department: 20, cod_monicipality: 20238},
  {name: "El Doncello", cod_department: 18, cod_monicipality: 18247},
  {name: "El Dorado", cod_department: 50, cod_monicipality: 50270},
  {name: "El Dovio", cod_department: 76, cod_monicipality: 76250},
  {name: "El Encanto", cod_department: 91, cod_monicipality: 91263},
  {name: "El Espino", cod_department: 15, cod_monicipality: 15248},
  {name: "El Guacamayo", cod_department: 68, cod_monicipality: 68245},
  {name: "El Guamo", cod_department: 13, cod_monicipality: 13248},
  {name: "El Litoral del San Juan", cod_department: 27, cod_monicipality: 27250},
  {name: "El Molino", cod_department: 44, cod_monicipality: 44110},
  {name: "El Paso", cod_department: 20, cod_monicipality: 20250},
  {name: "El Paujil", cod_department: 18, cod_monicipality: 18256},
  {name: "El Peñol", cod_department: 52, cod_monicipality: 52254},
  {name: "El Peñón", cod_department: 13, cod_monicipality: 13268},
  {name: "El Peñón", cod_department: 25, cod_monicipality: 25258},
  {name: "El Peñón", cod_department: 68, cod_monicipality: 68250},
  {name: "El Piñon", cod_department: 47, cod_monicipality: 47258},
  {name: "El Playón", cod_department: 68, cod_monicipality: 68255},
  {name: "El Retén", cod_department: 47, cod_monicipality: 47268},
  {name: "El Retorno", cod_department: 95, cod_monicipality: 95025},
  {name: "El Roble", cod_department: 70, cod_monicipality: 70233},
  {name: "El Rosal", cod_department: 25, cod_monicipality: 25260},
  {name: "El Rosario", cod_department: 52, cod_monicipality: 52256},
  {name: "El Santuario", cod_department: 5, cod_monicipality: 5697},
  {name: "El Tablón de Gómez", cod_department: 52, cod_monicipality: 52258},
  {name: "El Tambo", cod_department: 19, cod_monicipality: 19256},
  {name: "El Tambo", cod_department: 52, cod_monicipality: 52260},
  {name: "El Tarra", cod_department: 54, cod_monicipality: 54250},
  {name: "El Zulia", cod_department: 54, cod_monicipality: 54261},
  {name: "Elías", cod_department: 41, cod_monicipality: 41244},
  {name: "Encino", cod_department: 68, cod_monicipality: 68264},
  {name: "Enciso", cod_department: 68, cod_monicipality: 68266},
  {name: "Entrerrios", cod_department: 5, cod_monicipality: 5264},
  {name: "Envigado", cod_department: 5, cod_monicipality: 5266},
  {name: "Espinal", cod_department: 73, cod_monicipality: 73268},
  {name: "Facatativá", cod_department: 25, cod_monicipality: 25269},
  {name: "Falan", cod_department: 73, cod_monicipality: 73270},
  {name: "Filadelfia", cod_department: 17, cod_monicipality: 17272},
  {name: "Filandia", cod_department: 63, cod_monicipality: 63272},
  {name: "Firavitoba", cod_department: 15, cod_monicipality: 15272},
  {name: "Flandes", cod_department: 73, cod_monicipality: 73275},
  {name: "Florencia", cod_department: 18, cod_monicipality: 18001},
  {name: "Florencia", cod_department: 19, cod_monicipality: 19290},
  {name: "Floresta", cod_department: 15, cod_monicipality: 15276},
  {name: "Florián", cod_department: 68, cod_monicipality: 68271},
  {name: "Florida", cod_department: 76, cod_monicipality: 76275},
  {name: "Floridablanca", cod_department: 68, cod_monicipality: 68276},
  {name: "Fomeque", cod_department: 25, cod_monicipality: 25279},
  {name: "Fonseca", cod_department: 44, cod_monicipality: 44279},
  {name: "Fortul", cod_department: 81, cod_monicipality: 81300},
  {name: "Fosca", cod_department: 25, cod_monicipality: 25281},
  {name: "Francisco Pizarro", cod_department: 52, cod_monicipality: 52520},
  {name: "Fredonia", cod_department: 5, cod_monicipality: 5282},
  {name: "Fresno", cod_department: 73, cod_monicipality: 73283},
  {name: "Frontino", cod_department: 5, cod_monicipality: 5284},
  {name: "Fuente de Oro", cod_department: 50, cod_monicipality: 50287},
  {name: "Fundación", cod_department: 47, cod_monicipality: 47288},
  {name: "Funes", cod_department: 52, cod_monicipality: 52287},
  {name: "Funza", cod_department: 25, cod_monicipality: 25286},
  {name: "Fúquene", cod_department: 25, cod_monicipality: 25288},
  {name: "Fusagasugá", cod_department: 25, cod_monicipality: 25290},
  {name: "Gachala", cod_department: 25, cod_monicipality: 25293},
  {name: "Gachancipá", cod_department: 25, cod_monicipality: 25295},
  {name: "Gachantivá", cod_department: 15, cod_monicipality: 15293},
  {name: "Gachetá", cod_department: 25, cod_monicipality: 25297},
  {name: "Galán", cod_department: 68, cod_monicipality: 68296},
  {name: "Galapa", cod_department: 8, cod_monicipality: 8296},
  {name: "Galeras", cod_department: 70, cod_monicipality: 70235},
  {name: "Gama", cod_department: 25, cod_monicipality: 25299},
  {name: "Gamarra", cod_department: 20, cod_monicipality: 20295},
  {name: "Gambita", cod_department: 68, cod_monicipality: 68298},
  {name: "Gameza", cod_department: 15, cod_monicipality: 15296},
  {name: "Garagoa", cod_department: 15, cod_monicipality: 15299},
  {name: "Garzón", cod_department: 41, cod_monicipality: 41298},
  {name: "Génova", cod_department: 63, cod_monicipality: 63302},
  {name: "Gigante", cod_department: 41, cod_monicipality: 41306},
  {name: "Ginebra", cod_department: 76, cod_monicipality: 76306},
  {name: "Giraldo", cod_department: 5, cod_monicipality: 5306},
  {name: "Girardot", cod_department: 25, cod_monicipality: 25307},
  {name: "Girardota", cod_department: 5, cod_monicipality: 5308},
  {name: "Girón", cod_department: 68, cod_monicipality: 68307},
  {name: "Gómez Plata", cod_department: 5, cod_monicipality: 5310},
  {name: "González", cod_department: 20, cod_monicipality: 20310},
  {name: "Gramalote", cod_department: 54, cod_monicipality: 54313},
  {name: "Granada", cod_department: 5, cod_monicipality: 5313},
  {name: "Granada", cod_department: 25, cod_monicipality: 25312},
  {name: "Granada", cod_department: 50, cod_monicipality: 50313},
  {name: "Guaca", cod_department: 68, cod_monicipality: 68318},
  {name: "Guacamayas", cod_department: 15, cod_monicipality: 15317},
  {name: "Guacarí", cod_department: 76, cod_monicipality: 76318},
  {name: "Guachené", cod_department: 19, cod_monicipality: 19300},
  {name: "Guachetá", cod_department: 25, cod_monicipality: 25317},
  {name: "Guachucal", cod_department: 52, cod_monicipality: 52317},
  {name: "Guadalajara de Buga", cod_department: 76, cod_monicipality: 76111},
  {name: "Guadalupe", cod_department: 5, cod_monicipality: 5315},
  {name: "Guadalupe", cod_department: 41, cod_monicipality: 41319},
  {name: "Guadalupe", cod_department: 68, cod_monicipality: 68320},
  {name: "Guaduas", cod_department: 25, cod_monicipality: 25320},
  {name: "Guaitarilla", cod_department: 52, cod_monicipality: 52320},
  {name: "Gualmatán", cod_department: 52, cod_monicipality: 52323},
  {name: "Guamal", cod_department: 47, cod_monicipality: 47318},
  {name: "Guamal", cod_department: 50, cod_monicipality: 50318},
  {name: "Guamo", cod_department: 73, cod_monicipality: 73319},
  {name: "Guapi", cod_department: 19, cod_monicipality: 19318},
  {name: "Guapotá", cod_department: 68, cod_monicipality: 68322},
  {name: "Guaranda", cod_department: 70, cod_monicipality: 70265},
  {name: "Guarne", cod_department: 5, cod_monicipality: 5318},
  {name: "Guasca", cod_department: 25, cod_monicipality: 25322},
  {name: "Guatapé", cod_department: 5, cod_monicipality: 5321},
  {name: "Guataquí", cod_department: 25, cod_monicipality: 25324},
  {name: "Guatavita", cod_department: 25, cod_monicipality: 25326},
  {name: "Guateque", cod_department: 15, cod_monicipality: 15322},
  {name: "Guática", cod_department: 66, cod_monicipality: 66318},
  {name: "Guavatá", cod_department: 68, cod_monicipality: 68324},
  {name: "Guayabal de Siquima", cod_department: 25, cod_monicipality: 25328},
  {name: "Guayabetal", cod_department: 25, cod_monicipality: 25335},
  {name: "Guayatá", cod_department: 15, cod_monicipality: 15325},
  {name: "Güepsa", cod_department: 68, cod_monicipality: 68327},
  {name: "Güicán", cod_department: 15, cod_monicipality: 15332},
  {name: "Gutiérrez", cod_department: 25, cod_monicipality: 25339},
  {name: "Hacarí", cod_department: 54, cod_monicipality: 54344},
  {name: "Hatillo de Loba", cod_department: 13, cod_monicipality: 13300},
  {name: "Hato", cod_department: 68, cod_monicipality: 68344},
  {name: "Hato Corozal", cod_department: 85, cod_monicipality: 85125},
  {name: "Hatonuevo", cod_department: 44, cod_monicipality: 44378},
  {name: "Heliconia", cod_department: 5, cod_monicipality: 5347},
  {name: "Herrán", cod_department: 54, cod_monicipality: 54347},
  {name: "Herveo", cod_department: 73, cod_monicipality: 73347},
  {name: "Hispania", cod_department: 5, cod_monicipality: 5353},
  {name: "Hobo", cod_department: 41, cod_monicipality: 41349},
  {name: "Honda", cod_department: 73, cod_monicipality: 73349},
  {name: "Ibagué", cod_department: 73, cod_monicipality: 73001},
  {name: "Icononzo", cod_department: 73, cod_monicipality: 73352},
  {name: "Iles", cod_department: 52, cod_monicipality: 52352},
  {name: "Imués", cod_department: 52, cod_monicipality: 52354},
  {name: "Inírida", cod_department: 94, cod_monicipality: 94001},
  {name: "Inzá", cod_department: 19, cod_monicipality: 19355},
  {name: "Ipiales", cod_department: 52, cod_monicipality: 52356},
  {name: "Iquira", cod_department: 41, cod_monicipality: 41357},
  {name: "Isnos", cod_department: 41, cod_monicipality: 41359},
  {name: "Istmina", cod_department: 27, cod_monicipality: 27361},
  {name: "Itagui", cod_department: 5, cod_monicipality: 5360},
  {name: "Ituango", cod_department: 5, cod_monicipality: 5361},
  {name: "Iza", cod_department: 15, cod_monicipality: 15362},
  {name: "Jambaló", cod_department: 19, cod_monicipality: 19364},
  {name: "Jamundí", cod_department: 76, cod_monicipality: 76364},
  {name: "Jardín", cod_department: 5, cod_monicipality: 5364},
  {name: "Jenesano", cod_department: 15, cod_monicipality: 15367},
  {name: "Jericó", cod_department: 5, cod_monicipality: 5368},
  {name: "Jericó", cod_department: 15, cod_monicipality: 15368},
  {name: "Jerusalén", cod_department: 25, cod_monicipality: 25368},
  {name: "Jesús María", cod_department: 68, cod_monicipality: 68368},
  {name: "Jordán", cod_department: 68, cod_monicipality: 68370},
  {name: "Juan de Acosta", cod_department: 8, cod_monicipality: 8372},
  {name: "Junín", cod_department: 25, cod_monicipality: 25372},
  {name: "Juradó", cod_department: 27, cod_monicipality: 27372},
  {name: "La Apartada", cod_department: 23, cod_monicipality: 23350},
  {name: "La Argentina", cod_department: 41, cod_monicipality: 41378},
  {name: "La Belleza", cod_department: 68, cod_monicipality: 68377},
  {name: "La Calera", cod_department: 25, cod_monicipality: 25377},
  {name: "La Capilla", cod_department: 15, cod_monicipality: 15380},
  {name: "La Ceja", cod_department: 5, cod_monicipality: 5376},
  {name: "La Celia", cod_department: 66, cod_monicipality: 66383},
  {name: "La Chorrera", cod_department: 91, cod_monicipality: 91405},
  {name: "La Cruz", cod_department: 52, cod_monicipality: 52378},
  {name: "La Cumbre", cod_department: 76, cod_monicipality: 76377},
  {name: "La Dorada", cod_department: 17, cod_monicipality: 17380},
  {name: "La Esperanza", cod_department: 54, cod_monicipality: 54385},
  {name: "La Estrella", cod_department: 5, cod_monicipality: 5380},
  {name: "La Florida", cod_department: 52, cod_monicipality: 52381},
  {name: "La Gloria", cod_department: 20, cod_monicipality: 20383},
  {name: "La Guadalupe", cod_department: 94, cod_monicipality: 94885},
  {name: "La Jagua de Ibirico", cod_department: 20, cod_monicipality: 20400},
  {name: "La Jagua del Pilar", cod_department: 44, cod_monicipality: 44420},
  {name: "La Llanada", cod_department: 52, cod_monicipality: 52385},
  {name: "La Macarena", cod_department: 50, cod_monicipality: 50350},
  {name: "La Merced", cod_department: 17, cod_monicipality: 17388},
  {name: "La Mesa", cod_department: 25, cod_monicipality: 25386},
  {name: "La Montañita", cod_department: 18, cod_monicipality: 18410},
  {name: "La Palma", cod_department: 25, cod_monicipality: 25394},
  {name: "La Paz", cod_department: 20, cod_monicipality: 20621},
  {name: "La Paz", cod_department: 68, cod_monicipality: 68397},
  {name: "La Pedrera", cod_department: 91, cod_monicipality: 91407},
  {name: "La Peña", cod_department: 25, cod_monicipality: 25398},
  {name: "La Pintada", cod_department: 5, cod_monicipality: 5390},
  {name: "La Plata", cod_department: 41, cod_monicipality: 41396},
  {name: "La Playa", cod_department: 54, cod_monicipality: 54398},
  {name: "La Primavera", cod_department: 99, cod_monicipality: 99524},
  {name: "La Salina", cod_department: 85, cod_monicipality: 85136},
  {name: "La Sierra", cod_department: 19, cod_monicipality: 19392},
  {name: "La Tebaida", cod_department: 63, cod_monicipality: 63401},
  {name: "La Tola", cod_department: 52, cod_monicipality: 52390},
  {name: "La Unión", cod_department: 5, cod_monicipality: 5400},
  {name: "La Unión", cod_department: 52, cod_monicipality: 52399},
  {name: "La Unión", cod_department: 70, cod_monicipality: 70400},
  {name: "La Unión", cod_department: 76, cod_monicipality: 76400},
  {name: "La Uvita", cod_department: 15, cod_monicipality: 15403},
  {name: "La Vega", cod_department: 19, cod_monicipality: 19397},
  {name: "La Vega", cod_department: 25, cod_monicipality: 25402},
  {name: "La Victoria", cod_department: 15, cod_monicipality: 15401},
  {name: "La Victoria", cod_department: 76, cod_monicipality: 76403},
  {name: "La Victoria", cod_department: 91, cod_monicipality: 91430},
  {name: "La Virginia", cod_department: 66, cod_monicipality: 66400},
  {name: "Labateca", cod_department: 54, cod_monicipality: 54377},
  {name: "Labranzagrande", cod_department: 15, cod_monicipality: 15377},
  {name: "Landázuri", cod_department: 68, cod_monicipality: 68385},
  {name: "Lebríja", cod_department: 68, cod_monicipality: 68406},
  {name: "Leguízamo", cod_department: 86, cod_monicipality: 86573},
  {name: "Leiva", cod_department: 52, cod_monicipality: 52405},
  {name: "Lejanías", cod_department: 50, cod_monicipality: 50400},
  {name: "Lenguazaque", cod_department: 25, cod_monicipality: 25407},
  {name: "Lérida", cod_department: 73, cod_monicipality: 73408},
  {name: "Leticia", cod_department: 91, cod_monicipality: 91001},
  {name: "Líbano", cod_department: 73, cod_monicipality: 73411},
  {name: "Liborina", cod_department: 5, cod_monicipality: 5411},
  {name: "Linares", cod_department: 52, cod_monicipality: 52411},
  {name: "Lloró", cod_department: 27, cod_monicipality: 27413},
  {name: "López", cod_department: 19, cod_monicipality: 19418},
  {name: "Lorica", cod_department: 23, cod_monicipality: 23417},
  {name: "Los Andes", cod_department: 52, cod_monicipality: 52418},
  {name: "Los Córdobas", cod_department: 23, cod_monicipality: 23419},
  {name: "Los Palmitos", cod_department: 70, cod_monicipality: 70418},
  {name: "Los Patios", cod_department: 54, cod_monicipality: 54405},
  {name: "Los Santos", cod_department: 68, cod_monicipality: 68418},
  {name: "Lourdes", cod_department: 54, cod_monicipality: 54418},
  {name: "Luruaco", cod_department: 8, cod_monicipality: 8421},
  {name: "Macanal", cod_department: 15, cod_monicipality: 15425},
  {name: "Macaravita", cod_department: 68, cod_monicipality: 68425},
  {name: "Maceo", cod_department: 5, cod_monicipality: 5425},
  {name: "Macheta", cod_department: 25, cod_monicipality: 25426},
  {name: "Madrid", cod_department: 25, cod_monicipality: 25430},
  {name: "Magangué", cod_department: 13, cod_monicipality: 13430},
  {name: "Magüí", cod_department: 52, cod_monicipality: 52427},
  {name: "Mahates", cod_department: 13, cod_monicipality: 13433},
  {name: "Maicao", cod_department: 44, cod_monicipality: 44430},
  {name: "Majagual", cod_department: 70, cod_monicipality: 70429},
  {name: "Málaga", cod_department: 68, cod_monicipality: 68432},
  {name: "Malambo", cod_department: 8, cod_monicipality: 8433},
  {name: "Mallama", cod_department: 52, cod_monicipality: 52435},
  {name: "Manatí", cod_department: 8, cod_monicipality: 8436},
  {name: "Manaure", cod_department: 20, cod_monicipality: 20443},
  {name: "Manaure", cod_department: 44, cod_monicipality: 44560},
  {name: "Maní", cod_department: 85, cod_monicipality: 85139},
  {name: "Manizales", cod_department: 17, cod_monicipality: 17001},
  {name: "Manta", cod_department: 25, cod_monicipality: 25436},
  {name: "Manzanares", cod_department: 17, cod_monicipality: 17433},
  {name: "Mapiripán", cod_department: 50, cod_monicipality: 50325},
  {name: "Mapiripana", cod_department: 94, cod_monicipality: 94663},
  {name: "Margarita", cod_department: 13, cod_monicipality: 13440},
  {name: "María la Baja", cod_department: 13, cod_monicipality: 13442},
  {name: "Marinilla", cod_department: 5, cod_monicipality: 5440},
  {name: "Maripí", cod_department: 15, cod_monicipality: 15442},
  {name: "Mariquita", cod_department: 73, cod_monicipality: 73443},
  {name: "Marmato", cod_department: 17, cod_monicipality: 17442},
  {name: "Marquetalia", cod_department: 17, cod_monicipality: 17444},
  {name: "Marsella", cod_department: 66, cod_monicipality: 66440},
  {name: "Marulanda", cod_department: 17, cod_monicipality: 17446},
  {name: "Matanza", cod_department: 68, cod_monicipality: 68444},
  {name: "Medellín", cod_department: 5, cod_monicipality: 5001},
  {name: "Medina", cod_department: 25, cod_monicipality: 25438},
  {name: "Medio Atrato", cod_department: 27, cod_monicipality: 27425},
  {name: "Medio Baudó", cod_department: 27, cod_monicipality: 27430},
  {name: "Medio San Juan", cod_department: 27, cod_monicipality: 27450},
  {name: "Melgar", cod_department: 73, cod_monicipality: 73449},
  {name: "Mercaderes", cod_department: 19, cod_monicipality: 19450},
  {name: "Mesetas", cod_department: 50, cod_monicipality: 50330},
  {name: "Milán", cod_department: 18, cod_monicipality: 18460},
  {name: "Miraflores", cod_department: 15, cod_monicipality: 15455},
  {name: "Miraflores", cod_department: 95, cod_monicipality: 95200},
  {name: "Miranda", cod_department: 19, cod_monicipality: 19455},
  {name: "Miriti Paraná", cod_department: 91, cod_monicipality: 91460},
  {name: "Mistrató", cod_department: 66, cod_monicipality: 66456},
  {name: "Mitú", cod_department: 97, cod_monicipality: 97001},
  {name: "Mocoa", cod_department: 86, cod_monicipality: 86001},
  {name: "Mogotes", cod_department: 68, cod_monicipality: 68464},
  {name: "Molagavita", cod_department: 68, cod_monicipality: 68468},
  {name: "Momil", cod_department: 23, cod_monicipality: 23464},
  {name: "Mompós", cod_department: 13, cod_monicipality: 13468},
  {name: "Mongua", cod_department: 15, cod_monicipality: 15464},
  {name: "Monguí", cod_department: 15, cod_monicipality: 15466},
  {name: "Moniquirá", cod_department: 15, cod_monicipality: 15469},
  {name: "Montebello", cod_department: 5, cod_monicipality: 5467},
  {name: "Montecristo", cod_department: 13, cod_monicipality: 13458},
  {name: "Montelíbano", cod_department: 23, cod_monicipality: 23466},
  {name: "Montenegro", cod_department: 63, cod_monicipality: 63470},
  {name: "Montería", cod_department: 23, cod_monicipality: 23001},
  {name: "Monterrey", cod_department: 85, cod_monicipality: 85162},
  {name: "Moñitos", cod_department: 23, cod_monicipality: 23500},
  {name: "Morales", cod_department: 13, cod_monicipality: 13473},
  {name: "Morales", cod_department: 19, cod_monicipality: 19473},
  {name: "Morelia", cod_department: 18, cod_monicipality: 18479},
  {name: "Morichal", cod_department: 94, cod_monicipality: 94888},
  {name: "Morroa", cod_department: 70, cod_monicipality: 70473},
  {name: "Mosquera", cod_department: 25, cod_monicipality: 25473},
  {name: "Mosquera", cod_department: 52, cod_monicipality: 52473},
  {name: "Motavita", cod_department: 15, cod_monicipality: 15476},
  {name: "Murillo", cod_department: 73, cod_monicipality: 73461},
  {name: "Murindó", cod_department: 5, cod_monicipality: 5475},
  {name: "Mutatá", cod_department: 5, cod_monicipality: 5480},
  {name: "Mutiscua", cod_department: 54, cod_monicipality: 54480},
  {name: "Muzo", cod_department: 15, cod_monicipality: 15480},
  {name: "Nariño", cod_department: 5, cod_monicipality: 5483},
  {name: "Nariño", cod_department: 25, cod_monicipality: 25483},
  {name: "Nariño", cod_department: 52, cod_monicipality: 52480},
  {name: "Nátaga", cod_department: 41, cod_monicipality: 41483},
  {name: "Natagaima", cod_department: 73, cod_monicipality: 73483},
  {name: "Nechí", cod_department: 5, cod_monicipality: 5495},
  {name: "Necoclí", cod_department: 5, cod_monicipality: 5490},
  {name: "Neira", cod_department: 17, cod_monicipality: 17486},
  {name: "Neiva", cod_department: 41, cod_monicipality: 41001},
  {name: "Nemocón", cod_department: 25, cod_monicipality: 25486},
  {name: "Nilo", cod_department: 25, cod_monicipality: 25488},
  {name: "Nimaima", cod_department: 25, cod_monicipality: 25489},
  {name: "Nobsa", cod_department: 15, cod_monicipality: 15491},
  {name: "Nocaima", cod_department: 25, cod_monicipality: 25491},
  {name: "Norcasia", cod_department: 17, cod_monicipality: 17495},
  {name: "Norosí", cod_department: 13, cod_monicipality: 13490},
  {name: "Nóvita", cod_department: 27, cod_monicipality: 27491},
  {name: "Nueva Granada", cod_department: 47, cod_monicipality: 47460},
  {name: "Nuevo Colón", cod_department: 15, cod_monicipality: 15494},
  {name: "Nunchía", cod_department: 85, cod_monicipality: 85225},
  {name: "Nuquí", cod_department: 27, cod_monicipality: 27495},
  {name: "Obando", cod_department: 76, cod_monicipality: 76497},
  {name: "Ocamonte", cod_department: 68, cod_monicipality: 68498},
  {name: "Ocaña", cod_department: 54, cod_monicipality: 54498},
  {name: "Oiba", cod_department: 68, cod_monicipality: 68500},
  {name: "Oicatá", cod_department: 15, cod_monicipality: 15500},
  {name: "Olaya", cod_department: 5, cod_monicipality: 5501},
  {name: "Olaya Herrera", cod_department: 52, cod_monicipality: 52490},
  {name: "Onzaga", cod_department: 68, cod_monicipality: 68502},
  {name: "Oporapa", cod_department: 41, cod_monicipality: 41503},
  {name: "Orito", cod_department: 86, cod_monicipality: 86320},
  {name: "Orocué", cod_department: 85, cod_monicipality: 85230},
  {name: "Ortega", cod_department: 73, cod_monicipality: 73504},
  {name: "Ospina", cod_department: 52, cod_monicipality: 52506},
  {name: "Otanche", cod_department: 15, cod_monicipality: 15507},
  {name: "Ovejas", cod_department: 70, cod_monicipality: 70508},
  {name: "Pachavita", cod_department: 15, cod_monicipality: 15511},
  {name: "Pacho", cod_department: 25, cod_monicipality: 25513},
  {name: "Pacoa", cod_department: 97, cod_monicipality: 97511},
  {name: "Pácora", cod_department: 17, cod_monicipality: 17513},
  {name: "Padilla", cod_department: 19, cod_monicipality: 19513},
  {name: "Páez", cod_department: 15, cod_monicipality: 15514},
  {name: "Páez", cod_department: 19, cod_monicipality: 19517},
  {name: "Paicol", cod_department: 41, cod_monicipality: 41518},
  {name: "Pailitas", cod_department: 20, cod_monicipality: 20517},
  {name: "Paime", cod_department: 25, cod_monicipality: 25518},
  {name: "Paipa", cod_department: 15, cod_monicipality: 15516},
  {name: "Pajarito", cod_department: 15, cod_monicipality: 15518},
  {name: "Palermo", cod_department: 41, cod_monicipality: 41524},
  {name: "Palestina", cod_department: 17, cod_monicipality: 17524},
  {name: "Palestina", cod_department: 41, cod_monicipality: 41530},
  {name: "Palmar", cod_department: 68, cod_monicipality: 68522},
  {name: "Palmar de Varela", cod_department: 8, cod_monicipality: 8520},
  {name: "Palmas del Socorro", cod_department: 68, cod_monicipality: 68524},
  {name: "Palmira", cod_department: 76, cod_monicipality: 76520},
  {name: "Palmito", cod_department: 70, cod_monicipality: 70523},
  {name: "Palocabildo", cod_department: 73, cod_monicipality: 73520},
  {name: "Pamplona", cod_department: 54, cod_monicipality: 54518},
  {name: "Pamplonita", cod_department: 54, cod_monicipality: 54520},
  {name: "Pana Pana", cod_department: 94, cod_monicipality: 94887},
  {name: "Pandi", cod_department: 25, cod_monicipality: 25524},
  {name: "Panqueba", cod_department: 15, cod_monicipality: 15522},
  {name: "Papunaua", cod_department: 97, cod_monicipality: 97777},
  {name: "Páramo", cod_department: 68, cod_monicipality: 68533},
  {name: "Paratebueno", cod_department: 25, cod_monicipality: 25530},
  {name: "Pasca", cod_department: 25, cod_monicipality: 25535},
  {name: "Pasto", cod_department: 52, cod_monicipality: 52001},
  {name: "Patía", cod_department: 19, cod_monicipality: 19532},
  {name: "Pauna", cod_department: 15, cod_monicipality: 15531},
  {name: "Paya", cod_department: 15, cod_monicipality: 15533},
  {name: "Paz de Ariporo", cod_department: 85, cod_monicipality: 85250},
  {name: "Paz de Río", cod_department: 15, cod_monicipality: 15537},
  {name: "Pedraza", cod_department: 47, cod_monicipality: 47541},
  {name: "Pelaya", cod_department: 20, cod_monicipality: 20550},
  {name: "Pensilvania", cod_department: 17, cod_monicipality: 17541},
  {name: "Peñol", cod_department: 5, cod_monicipality: 5541},
  {name: "Peque", cod_department: 5, cod_monicipality: 5543},
  {name: "Pereira", cod_department: 66, cod_monicipality: 66001},
  {name: "Pesca", cod_department: 15, cod_monicipality: 15542},
  {name: "Piamonte", cod_department: 19, cod_monicipality: 19533},
  {name: "Piedecuesta", cod_department: 68, cod_monicipality: 68547},
  {name: "Piedras", cod_department: 73, cod_monicipality: 73547},
  {name: "Piendamó", cod_department: 19, cod_monicipality: 19548},
  {name: "Pijao", cod_department: 63, cod_monicipality: 63548},
  {name: "Pijiño del Carmen", cod_department: 47, cod_monicipality: 47545},
  {name: "Pinchote", cod_department: 68, cod_monicipality: 68549},
  {name: "Pinillos", cod_department: 13, cod_monicipality: 13549},
  {name: "Piojó", cod_department: 8, cod_monicipality: 8549},
  {name: "Pisba", cod_department: 15, cod_monicipality: 15550},
  {name: "Pital", cod_department: 41, cod_monicipality: 41548},
  {name: "Pitalito", cod_department: 41, cod_monicipality: 41551},
  {name: "Pivijay", cod_department: 47, cod_monicipality: 47551},
  {name: "Planadas", cod_department: 73, cod_monicipality: 73555},
  {name: "Planeta Rica", cod_department: 23, cod_monicipality: 23555},
  {name: "Plato", cod_department: 47, cod_monicipality: 47555},
  {name: "Policarpa", cod_department: 52, cod_monicipality: 52540},
  {name: "Polonuevo", cod_department: 8, cod_monicipality: 8558},
  {name: "Ponedera", cod_department: 8, cod_monicipality: 8560},
  {name: "Popayán", cod_department: 19, cod_monicipality: 19001},
  {name: "Pore", cod_department: 85, cod_monicipality: 85263},
  {name: "Potosí", cod_department: 52, cod_monicipality: 52560},
  {name: "Pradera", cod_department: 76, cod_monicipality: 76563},
  {name: "Prado", cod_department: 73, cod_monicipality: 73563},
  {name: "Providencia", cod_department: 52, cod_monicipality: 52565},
  {name: "Providencia", cod_department: 88, cod_monicipality: 88564},
  {name: "Pueblo Bello", cod_department: 20, cod_monicipality: 20570},
  {name: "Pueblo Nuevo", cod_department: 23, cod_monicipality: 23570},
  {name: "Pueblo Rico", cod_department: 66, cod_monicipality: 66572},
  {name: "Pueblo Viejo", cod_department: 47, cod_monicipality: 47570},
  {name: "Pueblorrico", cod_department: 5, cod_monicipality: 5576},
  {name: "Puente Nacional", cod_department: 68, cod_monicipality: 68572},
  {name: "Puerres", cod_department: 52, cod_monicipality: 52573},
  {name: "Puerto Alegría", cod_department: 91, cod_monicipality: 91530},
  {name: "Puerto Arica", cod_department: 91, cod_monicipality: 91536},
  {name: "Puerto Asís", cod_department: 86, cod_monicipality: 86568},
  {name: "Puerto Berrío", cod_department: 5, cod_monicipality: 5579},
  {name: "Puerto Boyacá", cod_department: 15, cod_monicipality: 15572},
  {name: "Puerto Caicedo", cod_department: 86, cod_monicipality: 86569},
  {name: "Puerto Carreño", cod_department: 99, cod_monicipality: 99001},
  {name: "Puerto Colombia", cod_department: 8, cod_monicipality: 8573},
  {name: "Puerto Colombia", cod_department: 94, cod_monicipality: 94884},
  {name: "Puerto Concordia", cod_department: 50, cod_monicipality: 50450},
  {name: "Puerto Escondido", cod_department: 23, cod_monicipality: 23574},
  {name: "Puerto Gaitán", cod_department: 50, cod_monicipality: 50568},
  {name: "Puerto Guzmán", cod_department: 86, cod_monicipality: 86571},
  {name: "Puerto Libertador", cod_department: 23, cod_monicipality: 23580},
  {name: "Puerto Lleras", cod_department: 50, cod_monicipality: 50577},
  {name: "Puerto López", cod_department: 50, cod_monicipality: 50573},
  {name: "Puerto Nare", cod_department: 5, cod_monicipality: 5585},
  {name: "Puerto Nariño", cod_department: 91, cod_monicipality: 91540},
  {name: "Puerto Parra", cod_department: 68, cod_monicipality: 68573},
  {name: "Puerto Rico", cod_department: 18, cod_monicipality: 18592},
  {name: "Puerto Rico", cod_department: 50, cod_monicipality: 50590},
  {name: "Puerto Rondón", cod_department: 81, cod_monicipality: 81591},
  {name: "Puerto Salgar", cod_department: 25, cod_monicipality: 25572},
  {name: "Puerto Santander", cod_department: 54, cod_monicipality: 54553},
  {name: "Puerto Santander", cod_department: 91, cod_monicipality: 91669},
  {name: "Puerto Tejada", cod_department: 19, cod_monicipality: 19573},
  {name: "Puerto Triunfo", cod_department: 5, cod_monicipality: 5591},
  {name: "Puerto Wilches", cod_department: 68, cod_monicipality: 68575},
  {name: "Pulí", cod_department: 25, cod_monicipality: 25580},
  {name: "Pupiales", cod_department: 52, cod_monicipality: 52585},
  {name: "Puracé", cod_department: 19, cod_monicipality: 19585},
  {name: "Purificación", cod_department: 73, cod_monicipality: 73585},
  {name: "Purísima", cod_department: 23, cod_monicipality: 23586},
  {name: "Quebradanegra", cod_department: 25, cod_monicipality: 25592},
  {name: "Quetame", cod_department: 25, cod_monicipality: 25594},
  {name: "Quibdó", cod_department: 27, cod_monicipality: 27001},
  {name: "Quimbaya", cod_department: 63, cod_monicipality: 63594},
  {name: "Quinchía", cod_department: 66, cod_monicipality: 66594},
  {name: "Quípama", cod_department: 15, cod_monicipality: 15580},
  {name: "Quipile", cod_department: 25, cod_monicipality: 25596},
  {name: "Ragonvalia", cod_department: 54, cod_monicipality: 54599},
  {name: "Ramiriquí", cod_department: 15, cod_monicipality: 15599},
  {name: "Ráquira", cod_department: 15, cod_monicipality: 15600},
  {name: "Recetor", cod_department: 85, cod_monicipality: 85279},
  {name: "Regidor", cod_department: 13, cod_monicipality: 13580},
  {name: "Remedios", cod_department: 5, cod_monicipality: 5604},
  {name: "Remolino", cod_department: 47, cod_monicipality: 47605},
  {name: "Repelón", cod_department: 8, cod_monicipality: 8606},
  {name: "Restrepo", cod_department: 50, cod_monicipality: 50606},
  {name: "Restrepo", cod_department: 76, cod_monicipality: 76606},
  {name: "Retiro", cod_department: 5, cod_monicipality: 5607},
  {name: "Ricaurte", cod_department: 25, cod_monicipality: 25612},
  {name: "Ricaurte", cod_department: 52, cod_monicipality: 52612},
  {name: "Rio Blanco", cod_department: 73, cod_monicipality: 73616},
  {name: "Río de Oro", cod_department: 20, cod_monicipality: 20614},
  {name: "Río Iro", cod_department: 27, cod_monicipality: 27580},
  {name: "Río Quito", cod_department: 27, cod_monicipality: 27600},
  {name: "Río Viejo", cod_department: 13, cod_monicipality: 13600},
  {name: "Riofrío", cod_department: 76, cod_monicipality: 76616},
  {name: "Riohacha", cod_department: 44, cod_monicipality: 44001},
  {name: "Rionegro", cod_department: 5, cod_monicipality: 5615},
  {name: "Rionegro", cod_department: 68, cod_monicipality: 68615},
  {name: "Riosucio", cod_department: 17, cod_monicipality: 17614},
  {name: "Riosucio", cod_department: 27, cod_monicipality: 27615},
  {name: "Risaralda", cod_department: 17, cod_monicipality: 17616},
  {name: "Rivera", cod_department: 41, cod_monicipality: 41615},
  {name: "Roberto Payán", cod_department: 52, cod_monicipality: 52621},
  {name: "Roldanillo", cod_department: 76, cod_monicipality: 76622},
  {name: "Roncesvalles", cod_department: 73, cod_monicipality: 73622},
  {name: "Rondón", cod_department: 15, cod_monicipality: 15621},
  {name: "Rosas", cod_department: 19, cod_monicipality: 19622},
  {name: "Rovira", cod_department: 73, cod_monicipality: 73624},
  {name: "Sabana de Torres", cod_department: 68, cod_monicipality: 68655},
  {name: "Sabanagrande", cod_department: 8, cod_monicipality: 8634},
  {name: "Sabanalarga", cod_department: 5, cod_monicipality: 5628},
  {name: "Sabanalarga", cod_department: 8, cod_monicipality: 8638},
  {name: "Sabanalarga", cod_department: 85, cod_monicipality: 85300},
  {name: "Sabanas de San Angel", cod_department: 47, cod_monicipality: 47660},
  {name: "Sabaneta", cod_department: 5, cod_monicipality: 5631},
  {name: "Saboyá", cod_department: 15, cod_monicipality: 15632},
  {name: "Sácama", cod_department: 85, cod_monicipality: 85315},
  {name: "Sáchica", cod_department: 15, cod_monicipality: 15638},
  {name: "Sahagún", cod_department: 23, cod_monicipality: 23660},
  {name: "Saladoblanco", cod_department: 41, cod_monicipality: 41660},
  {name: "Salamina", cod_department: 17, cod_monicipality: 17653},
  {name: "Salamina", cod_department: 47, cod_monicipality: 47675},
  {name: "Salazar", cod_department: 54, cod_monicipality: 54660},
  {name: "Saldaña", cod_department: 73, cod_monicipality: 73671},
  {name: "Salento", cod_department: 63, cod_monicipality: 63690},
  {name: "Salgar", cod_department: 5, cod_monicipality: 5642},
  {name: "Samacá", cod_department: 15, cod_monicipality: 15646},
  {name: "Samaná", cod_department: 17, cod_monicipality: 17662},
  {name: "Samaniego", cod_department: 52, cod_monicipality: 52678},
  {name: "Sampués", cod_department: 70, cod_monicipality: 70670},
  {name: "San Agustín", cod_department: 41, cod_monicipality: 41668},
  {name: "San Alberto", cod_department: 20, cod_monicipality: 20710},
  {name: "San Andrés", cod_department: 68, cod_monicipality: 68669},
  {name: "San Andrés", cod_department: 88, cod_monicipality: 88001},
  {name: "San Andrés de Cuerquía", cod_department: 5, cod_monicipality: 5647},
  {name: "San Andrés de Tumaco", cod_department: 52, cod_monicipality: 52835},
  {name: "San Andrés Sotavento", cod_department: 23, cod_monicipality: 23670},
  {name: "San Antero", cod_department: 23, cod_monicipality: 23672},
  {name: "San Antonio", cod_department: 73, cod_monicipality: 73675},
  {name: "San Antonio del Tequendama", cod_department: 25, cod_monicipality: 25645},
  {name: "San Benito", cod_department: 68, cod_monicipality: 68673},
  {name: "San Benito Abad", cod_department: 70, cod_monicipality: 70678},
  {name: "San Bernardo", cod_department: 25, cod_monicipality: 25649},
  {name: "San Bernardo", cod_department: 52, cod_monicipality: 52685},
  {name: "San Bernardo del Viento", cod_department: 23, cod_monicipality: 23675},
  {name: "San Calixto", cod_department: 54, cod_monicipality: 54670},
  {name: "San Carlos", cod_department: 5, cod_monicipality: 5649},
  {name: "San Carlos", cod_department: 23, cod_monicipality: 23678},
  {name: "San Carlos de Guaroa", cod_department: 50, cod_monicipality: 50680},
  {name: "San Cayetano", cod_department: 25, cod_monicipality: 25653},
  {name: "San Cayetano", cod_department: 54, cod_monicipality: 54673},
  {name: "San Cristóbal", cod_department: 13, cod_monicipality: 13620},
  {name: "San Diego", cod_department: 20, cod_monicipality: 20750},
  {name: "San Eduardo", cod_department: 15, cod_monicipality: 15660},
  {name: "San Estanislao", cod_department: 13, cod_monicipality: 13647},
  {name: "San Felipe", cod_department: 94, cod_monicipality: 94883},
  {name: "San Fernando", cod_department: 13, cod_monicipality: 13650},
  {name: "San Francisco", cod_department: 5, cod_monicipality: 5652},
  {name: "San Francisco", cod_department: 25, cod_monicipality: 25658},
  {name: "San Francisco", cod_department: 86, cod_monicipality: 86755},
  {name: "San Gil", cod_department: 68, cod_monicipality: 68679},
  {name: "San Jacinto", cod_department: 13, cod_monicipality: 13654},
  {name: "San Jacinto del Cauca", cod_department: 13, cod_monicipality: 13655},
  {name: "San Jerónimo", cod_department: 5, cod_monicipality: 5656},
  {name: "San Joaquín", cod_department: 68, cod_monicipality: 68682},
  {name: "San José", cod_department: 17, cod_monicipality: 17665},
  {name: "San José de La Montaña", cod_department: 5, cod_monicipality: 5658},
  {name: "San José de Miranda", cod_department: 68, cod_monicipality: 68684},
  {name: "San José de Pare", cod_department: 15, cod_monicipality: 15664},
  {name: "San José de Uré", cod_department: 23, cod_monicipality: 23682},
  {name: "San José del Fragua", cod_department: 18, cod_monicipality: 18610},
  {name: "San José del Guaviare", cod_department: 95, cod_monicipality: 95001},
  {name: "San José del Palmar", cod_department: 27, cod_monicipality: 27660},
  {name: "San Juan de Arama", cod_department: 50, cod_monicipality: 50683},
  {name: "San Juan de Betulia", cod_department: 70, cod_monicipality: 70702},
  {name: "San Juan de Río Seco", cod_department: 25, cod_monicipality: 25662},
  {name: "San Juan de Urabá", cod_department: 5, cod_monicipality: 5659},
  {name: "San Juan del Cesar", cod_department: 44, cod_monicipality: 44650},
  {name: "San Juan Nepomuceno", cod_department: 13, cod_monicipality: 13657},
  {name: "San Juanito", cod_department: 50, cod_monicipality: 50686},
  {name: "San Lorenzo", cod_department: 52, cod_monicipality: 52687},
  {name: "San Luis", cod_department: 5, cod_monicipality: 5660},
  {name: "San Luis", cod_department: 73, cod_monicipality: 73678},
  {name: "San Luis de Gaceno", cod_department: 15, cod_monicipality: 15667},
  {name: "San Luis de Gaceno", cod_department: 85, cod_monicipality: 85325},
  {name: "San Luis de Sincé", cod_department: 70, cod_monicipality: 70742},
  {name: "San Marcos", cod_department: 70, cod_monicipality: 70708},
  {name: "San Martín", cod_department: 20, cod_monicipality: 20770},
  {name: "San Martín", cod_department: 50, cod_monicipality: 50689},
  {name: "San Martín de Loba", cod_department: 13, cod_monicipality: 13667},
  {name: "San Mateo", cod_department: 15, cod_monicipality: 15673},
  {name: "San Miguel", cod_department: 68, cod_monicipality: 68686},
  {name: "San Miguel", cod_department: 86, cod_monicipality: 86757},
  {name: "San Miguel de Sema", cod_department: 15, cod_monicipality: 15676},
  {name: "San Onofre", cod_department: 70, cod_monicipality: 70713},
  {name: "San Pablo", cod_department: 52, cod_monicipality: 52693},
  {name: "San Pablo de Borbur", cod_department: 13, cod_monicipality: 13670},
  {name: "San Pablo de Borbur", cod_department: 15, cod_monicipality: 15681},
  {name: "San Pedro", cod_department: 5, cod_monicipality: 5664},
  {name: "San Pedro", cod_department: 70, cod_monicipality: 70717},
  {name: "San Pedro", cod_department: 76, cod_monicipality: 76670},
  {name: "San Pedro de Cartago", cod_department: 52, cod_monicipality: 52694},
  {name: "San Pedro de Uraba", cod_department: 5, cod_monicipality: 5665},
  {name: "San Pelayo", cod_department: 23, cod_monicipality: 23686},
  {name: "San Rafael", cod_department: 5, cod_monicipality: 5667},
  {name: "San Roque", cod_department: 5, cod_monicipality: 5670},
  {name: "San Sebastián", cod_department: 19, cod_monicipality: 19693},
  {name: "San Sebastián de Buenavista", cod_department: 47, cod_monicipality: 47692},
  {name: "San Vicente", cod_department: 5, cod_monicipality: 5674},
  {name: "San Vicente de Chucurí", cod_department: 68, cod_monicipality: 68689},
  {name: "San Vicente del Caguán", cod_department: 18, cod_monicipality: 18753},
  {name: "San Zenón", cod_department: 47, cod_monicipality: 47703},
  {name: "Sandoná", cod_department: 52, cod_monicipality: 52683},
  {name: "Santa Ana", cod_department: 47, cod_monicipality: 47707},
  {name: "Santa Bárbara", cod_department: 5, cod_monicipality: 5679},
  {name: "Santa Bárbara", cod_department: 52, cod_monicipality: 52696},
  {name: "Santa Bárbara", cod_department: 68, cod_monicipality: 68705},
  {name: "Santa Bárbara de Pinto", cod_department: 47, cod_monicipality: 47720},
  {name: "Santa Catalina", cod_department: 13, cod_monicipality: 13673},
  {name: "Socha", cod_department: 15, cod_monicipality: 15757},
  {name: "Santa Helena del Opón", cod_department: 68, cod_monicipality: 68720},
  {name: "Santa Isabel", cod_department: 73, cod_monicipality: 73686},
  {name: "Santa Lucía", cod_department: 8, cod_monicipality: 8675},
  {name: "Santa María", cod_department: 15, cod_monicipality: 15690},
  {name: "Santa María", cod_department: 41, cod_monicipality: 41676},
  {name: "Santa Marta", cod_department: 47, cod_monicipality: 47001},
  {name: "Santa Rosa", cod_department: 13, cod_monicipality: 13683},
  {name: "Santa Rosa", cod_department: 19, cod_monicipality: 19701},
  {name: "Santa Rosa de Cabal", cod_department: 66, cod_monicipality: 66682},
  {name: "Santa Rosa de Osos", cod_department: 5, cod_monicipality: 5686},
  {name: "Santa Rosa de Viterbo", cod_department: 15, cod_monicipality: 15693},
  {name: "Santa Rosa del Sur", cod_department: 13, cod_monicipality: 13688},
  {name: "Santa Rosalía", cod_department: 99, cod_monicipality: 99624},
  {name: "Santa Sofía", cod_department: 15, cod_monicipality: 15696},
  {name: "Santacruz", cod_department: 52, cod_monicipality: 52699},
  {name: "Santafé de Antioquia", cod_department: 5, cod_monicipality: 5042},
  {name: "Santana", cod_department: 15, cod_monicipality: 15686},
  {name: "Santander de Quilichao", cod_department: 19, cod_monicipality: 19698},
  {name: "Santiago", cod_department: 54, cod_monicipality: 54680},
  {name: "Santiago", cod_department: 86, cod_monicipality: 86760},
  {name: "Santiago de Tolú", cod_department: 70, cod_monicipality: 70820},
  {name: "Santo Domingo", cod_department: 5, cod_monicipality: 5690},
  {name: "Santo Tomás", cod_department: 8, cod_monicipality: 8685},
  {name: "Santuario", cod_department: 66, cod_monicipality: 66687},
  {name: "Sapuyes", cod_department: 52, cod_monicipality: 52720},
  {name: "Saravena", cod_department: 81, cod_monicipality: 81736},
  {name: "Sardinata", cod_department: 54, cod_monicipality: 54720},
  {name: "Sasaima", cod_department: 25, cod_monicipality: 25718},
  {name: "Sativanorte", cod_department: 15, cod_monicipality: 15720},
  {name: "Sativasur", cod_department: 15, cod_monicipality: 15723},
  {name: "Segovia", cod_department: 5, cod_monicipality: 5736},
  {name: "Sesquilé", cod_department: 25, cod_monicipality: 25736},
  {name: "Sevilla", cod_department: 76, cod_monicipality: 76736},
  {name: "Siachoque", cod_department: 15, cod_monicipality: 15740},
  {name: "Sibaté", cod_department: 25, cod_monicipality: 25740},
  {name: "Sibundoy", cod_department: 86, cod_monicipality: 86749},
  {name: "Silos", cod_department: 54, cod_monicipality: 54743},
  {name: "Silvania", cod_department: 25, cod_monicipality: 25743},
  {name: "Silvia", cod_department: 19, cod_monicipality: 19743},
  {name: "Simacota", cod_department: 68, cod_monicipality: 68745},
  {name: "Simijaca", cod_department: 25, cod_monicipality: 25745},
  {name: "Simití", cod_department: 13, cod_monicipality: 13744},
  {name: "Sincelejo", cod_department: 70, cod_monicipality: 70001},
  {name: "Sipí", cod_department: 27, cod_monicipality: 27745},
  {name: "Sitionuevo", cod_department: 47, cod_monicipality: 47745},
  {name: "Soacha", cod_department: 25, cod_monicipality: 25754},
  {name: "Soatá", cod_department: 15, cod_monicipality: 15753},
  {name: "Socorro", cod_department: 68, cod_monicipality: 68755},
  {name: "Socotá", cod_department: 15, cod_monicipality: 15755},
  {name: "Sogamoso", cod_department: 15, cod_monicipality: 15759},
  {name: "Solano", cod_department: 18, cod_monicipality: 18756},
  {name: "Soledad", cod_department: 8, cod_monicipality: 8758},
  {name: "Solita", cod_department: 18, cod_monicipality: 18785},
  {name: "Somondoco", cod_department: 15, cod_monicipality: 15761},
  {name: "Sonsón", cod_department: 5, cod_monicipality: 5756},
  {name: "Sopetrán", cod_department: 5, cod_monicipality: 5761},
  {name: "Soplaviento", cod_department: 13, cod_monicipality: 13760},
  {name: "Sopó", cod_department: 25, cod_monicipality: 25758},
  {name: "Sora", cod_department: 15, cod_monicipality: 15762},
  {name: "Soracá", cod_department: 15, cod_monicipality: 15764},
  {name: "Sotaquirá", cod_department: 15, cod_monicipality: 15763},
  {name: "Sotara", cod_department: 19, cod_monicipality: 19760},
  {name: "Suaita", cod_department: 68, cod_monicipality: 68770},
  {name: "Suan", cod_department: 8, cod_monicipality: 8770},
  {name: "Suárez", cod_department: 19, cod_monicipality: 19780},
  {name: "Suárez", cod_department: 73, cod_monicipality: 73770},
  {name: "Suaza", cod_department: 41, cod_monicipality: 41770},
  {name: "Subachoque", cod_department: 25, cod_monicipality: 25769},
  {name: "Sucre", cod_department: 19, cod_monicipality: 19785},
  {name: "Sucre", cod_department: 68, cod_monicipality: 68773},
  {name: "Sucre", cod_department: 70, cod_monicipality: 70771},
  {name: "Suesca", cod_department: 25, cod_monicipality: 25772},
  {name: "Supatá", cod_department: 25, cod_monicipality: 25777},
  {name: "Supía", cod_department: 17, cod_monicipality: 17777},
  {name: "Suratá", cod_department: 68, cod_monicipality: 68780},
  {name: "Susa", cod_department: 25, cod_monicipality: 25779},
  {name: "Susacón", cod_department: 15, cod_monicipality: 15774},
  {name: "Sutamarchán", cod_department: 15, cod_monicipality: 15776},
  {name: "Sutatausa", cod_department: 25, cod_monicipality: 25781},
  {name: "Sutatenza", cod_department: 15, cod_monicipality: 15778},
  {name: "Tabio", cod_department: 25, cod_monicipality: 25785},
  {name: "Tadó", cod_department: 27, cod_monicipality: 27787},
  {name: "Talaigua Nuevo", cod_department: 13, cod_monicipality: 13780},
  {name: "Tamalameque", cod_department: 20, cod_monicipality: 20787},
  {name: "Támara", cod_department: 85, cod_monicipality: 85400},
  {name: "Tame", cod_department: 81, cod_monicipality: 81794},
  {name: "Támesis", cod_department: 5, cod_monicipality: 5789},
  {name: "Taminango", cod_department: 52, cod_monicipality: 52786},
  {name: "Tangua", cod_department: 52, cod_monicipality: 52788},
  {name: "Taraira", cod_department: 97, cod_monicipality: 97666},
  {name: "Tarapacá", cod_department: 91, cod_monicipality: 91798},
  {name: "Tarazá", cod_department: 5, cod_monicipality: 5790},
  {name: "Tarqui", cod_department: 41, cod_monicipality: 41791},
  {name: "Tarso", cod_department: 5, cod_monicipality: 5792},
  {name: "Tasco", cod_department: 15, cod_monicipality: 15790},
  {name: "Tauramena", cod_department: 85, cod_monicipality: 85410},
  {name: "Tausa", cod_department: 25, cod_monicipality: 25793},
  {name: "Tello", cod_department: 41, cod_monicipality: 41799},
  {name: "Tena", cod_department: 25, cod_monicipality: 25797},
  {name: "Tenerife", cod_department: 47, cod_monicipality: 47798},
  {name: "Tenjo", cod_department: 25, cod_monicipality: 25799},
  {name: "Tenza", cod_department: 15, cod_monicipality: 15798},
  {name: "Teorama", cod_department: 54, cod_monicipality: 54800},
  {name: "Teruel", cod_department: 41, cod_monicipality: 41801},
  {name: "Tesalia", cod_department: 41, cod_monicipality: 41797},
  {name: "Tibacuy", cod_department: 25, cod_monicipality: 25805},
  {name: "Tibaná", cod_department: 15, cod_monicipality: 15804},
  {name: "Tibasosa", cod_department: 15, cod_monicipality: 15806},
  {name: "Tibirita", cod_department: 25, cod_monicipality: 25807},
  {name: "Tibú", cod_department: 54, cod_monicipality: 54810},
  {name: "Tierralta", cod_department: 23, cod_monicipality: 23807},
  {name: "Timaná", cod_department: 41, cod_monicipality: 41807},
  {name: "Timbío", cod_department: 19, cod_monicipality: 19807},
  {name: "Timbiquí", cod_department: 19, cod_monicipality: 19809},
  {name: "Tinjacá", cod_department: 15, cod_monicipality: 15808},
  {name: "Tipacoque", cod_department: 15, cod_monicipality: 15810},
  {name: "Tiquisio", cod_department: 13, cod_monicipality: 13810},
  {name: "Titiribí", cod_department: 5, cod_monicipality: 5809},
  {name: "Toca", cod_department: 15, cod_monicipality: 15814},
  {name: "Tocaima", cod_department: 25, cod_monicipality: 25815},
  {name: "Tocancipá", cod_department: 25, cod_monicipality: 25817},
  {name: "Togüí", cod_department: 15, cod_monicipality: 15816},
  {name: "Toledo", cod_department: 5, cod_monicipality: 5819},
  {name: "Toledo", cod_department: 54, cod_monicipality: 54820},
  {name: "Tolú Viejo", cod_department: 70, cod_monicipality: 70823},
  {name: "Tona", cod_department: 68, cod_monicipality: 68820},
  {name: "Tópaga", cod_department: 15, cod_monicipality: 15820},
  {name: "Topaipí", cod_department: 25, cod_monicipality: 25823},
  {name: "Toribio", cod_department: 19, cod_monicipality: 19821},
  {name: "Toro", cod_department: 76, cod_monicipality: 76823},
  {name: "Tota", cod_department: 15, cod_monicipality: 15822},
  {name: "Totoró", cod_department: 19, cod_monicipality: 19824},
  {name: "Trinidad", cod_department: 85, cod_monicipality: 85430},
  {name: "Trujillo", cod_department: 76, cod_monicipality: 76828},
  {name: "Tubará", cod_department: 8, cod_monicipality: 8832},
  {name: "Tuchín", cod_department: 23, cod_monicipality: 23815},
  {name: "Tuluá", cod_department: 76, cod_monicipality: 76834},
  {name: "Tunja", cod_department: 15, cod_monicipality: 15001},
  {name: "Tununguá", cod_department: 15, cod_monicipality: 15832},
  {name: "Túquerres", cod_department: 52, cod_monicipality: 52838},
  {name: "Turbaco", cod_department: 13, cod_monicipality: 13836},
  {name: "Turbaná", cod_department: 13, cod_monicipality: 13838},
  {name: "Turbo", cod_department: 5, cod_monicipality: 5837},
  {name: "Turmequé", cod_department: 15, cod_monicipality: 15835},
  {name: "Tuta", cod_department: 15, cod_monicipality: 15837},
  {name: "Tutazá", cod_department: 15, cod_monicipality: 15839},
  {name: "Ubalá", cod_department: 25, cod_monicipality: 25839},
  {name: "Ubaque", cod_department: 25, cod_monicipality: 25841},
  {name: "Ulloa", cod_department: 76, cod_monicipality: 76845},
  {name: "Umbita", cod_department: 15, cod_monicipality: 15842},
  {name: "Une", cod_department: 25, cod_monicipality: 25845},
  {name: "Unguía", cod_department: 27, cod_monicipality: 27800},
  {name: "Unión Panamericana", cod_department: 27, cod_monicipality: 27810},
  {name: "Uramita", cod_department: 5, cod_monicipality: 5842},
  {name: "Uribe", cod_department: 50, cod_monicipality: 50370},
  {name: "Uribia", cod_department: 44, cod_monicipality: 44847},
  {name: "Urrao", cod_department: 5, cod_monicipality: 5847},
  {name: "Urumita", cod_department: 44, cod_monicipality: 44855},
  {name: "Usiacurí", cod_department: 8, cod_monicipality: 8849},
  {name: "Útica", cod_department: 25, cod_monicipality: 25851},
  {name: "Valdivia", cod_department: 5, cod_monicipality: 5854},
  {name: "Valencia", cod_department: 23, cod_monicipality: 23855},
  {name: "Valle de Guamez", cod_department: 86, cod_monicipality: 86865},
  {name: "Valle de San José", cod_department: 68, cod_monicipality: 68855},
  {name: "Valle de San Juan", cod_department: 73, cod_monicipality: 73854},
  {name: "Valledupar", cod_department: 20, cod_monicipality: 20001},
  {name: "Valparaíso", cod_department: 5, cod_monicipality: 5856},
  {name: "Valparaíso", cod_department: 18, cod_monicipality: 18860},
  {name: "Vegachí", cod_department: 5, cod_monicipality: 5858},
  {name: "Vélez", cod_department: 68, cod_monicipality: 68861},
  {name: "Venadillo", cod_department: 73, cod_monicipality: 73861},
  {name: "Venecia", cod_department: 5, cod_monicipality: 5861},
  {name: "Venecia", cod_department: 25, cod_monicipality: 25506},
  {name: "Ventaquemada", cod_department: 15, cod_monicipality: 15861},
  {name: "Vergara", cod_department: 25, cod_monicipality: 25862},
  {name: "Versalles", cod_department: 76, cod_monicipality: 76863},
  {name: "Vetas", cod_department: 68, cod_monicipality: 68867},
  {name: "Vianí", cod_department: 25, cod_monicipality: 25867},
  {name: "Victoria", cod_department: 17, cod_monicipality: 17867},
  {name: "Vigía del Fuerte", cod_department: 5, cod_monicipality: 5873},
  {name: "Vijes", cod_department: 76, cod_monicipality: 76869},
  {name: "Villa Caro", cod_department: 54, cod_monicipality: 54871},
  {name: "Villa de Leyva", cod_department: 15, cod_monicipality: 15407},
  {name: "Villa de San Diego de Ubate", cod_department: 25, cod_monicipality: 25843},
  {name: "Villa del Rosario", cod_department: 54, cod_monicipality: 54874},
  {name: "Villa Rica", cod_department: 19, cod_monicipality: 19845},
  {name: "Villagarzón", cod_department: 86, cod_monicipality: 86885},
  {name: "Villagómez", cod_department: 25, cod_monicipality: 25871},
  {name: "Villahermosa", cod_department: 73, cod_monicipality: 73870},
  {name: "Villamaría", cod_department: 17, cod_monicipality: 17873},
  {name: "Villanueva", cod_department: 13, cod_monicipality: 13873},
  {name: "Villanueva", cod_department: 44, cod_monicipality: 44874},
  {name: "Villanueva", cod_department: 68, cod_monicipality: 68872},
  {name: "Villanueva", cod_department: 85, cod_monicipality: 85440},
  {name: "Villapinzón", cod_department: 25, cod_monicipality: 25873},
  {name: "Villarrica", cod_department: 73, cod_monicipality: 73873},
  {name: "Villavicencio", cod_department: 50, cod_monicipality: 50001},
  {name: "Villavieja", cod_department: 41, cod_monicipality: 41872},
  {name: "Villeta", cod_department: 25, cod_monicipality: 25875},
  {name: "Viotá", cod_department: 25, cod_monicipality: 25878},
  {name: "Viracachá", cod_department: 15, cod_monicipality: 15879},
  {name: "Vista Hermosa", cod_department: 50, cod_monicipality: 50711},
  {name: "Viterbo", cod_department: 17, cod_monicipality: 17877},
  {name: "Yacopí", cod_department: 25, cod_monicipality: 25885},
  {name: "Yacuanquer", cod_department: 52, cod_monicipality: 52885},
  {name: "Yaguará", cod_department: 41, cod_monicipality: 41885},
  {name: "Yalí", cod_department: 5, cod_monicipality: 5885},
  {name: "Yarumal", cod_department: 5, cod_monicipality: 5887},
  {name: "Yavaraté", cod_department: 97, cod_monicipality: 97889},
  {name: "Yolombó", cod_department: 5, cod_monicipality: 5890},
  {name: "Yondó", cod_department: 5, cod_monicipality: 5893},
  {name: "Yopal", cod_department: 85, cod_monicipality: 85001},
  {name: "Yotoco", cod_department: 76, cod_monicipality: 76890},
  {name: "Yumbo", cod_department: 76, cod_monicipality: 76892},
  {name: "Zambrano", cod_department: 13, cod_monicipality: 13894},
  {name: "Zapatoca", cod_department: 68, cod_monicipality: 68895},
  {name: "Zapayán", cod_department: 47, cod_monicipality: 47960},
  {name: "Zaragoza", cod_department: 5, cod_monicipality: 5895},
  {name: "Zarzal", cod_department: 76, cod_monicipality: 76895},
  {name: "Zetaquira", cod_department: 15, cod_monicipality: 15897},
  {name: "Zipacón", cod_department: 25, cod_monicipality: 25898},
  {name: "Zipaquirá", cod_department: 25, cod_monicipality: 25899},
  {name: "Zona Bananera", cod_department: 47, cod_monicipality: 47980},
  {name: "Ghana", cod_department: 999, cod_municipality: nil},
  {name: "Alemania", cod_department: 999, cod_municipality: nil},
  {name: "Arzerbaiyan", cod_department: 999, cod_municipality: nil},
  {name: "Curazao", cod_department: 999, cod_municipality: nil},
  {name: "Argentina", cod_department: 999, cod_municipality: nil},
  {name: "Aruba", cod_department: 999, cod_municipality: nil},
  {name: "Australia", cod_department: 999, cod_municipality: nil},
  {name: "Austria", cod_department: 999, cod_municipality: nil},
  {name: "Belgica", cod_department: 999, cod_municipality: nil},
  {name: "Bolivia", cod_department: 999, cod_municipality: nil},
  {name: "Brasil", cod_department: 999, cod_municipality: nil},
  {name: "Canada", cod_department: 999, cod_municipality: nil},
  {name: "Corea Del Sur", cod_department: 999, cod_municipality: nil},
  {name: "Costa Rica", cod_department: 999, cod_municipality: nil},
  {name: "Cuba", cod_department: 999, cod_municipality: nil},
  {name: "Chile", cod_department: 999, cod_municipality: nil},
  {name: "China Republica Popular", cod_department: 999, cod_municipality: nil},
  {name: "Chipre", cod_department: 999, cod_municipality: nil},
  {name: "Dinamarca", cod_department: 999, cod_municipality: nil},
  {name: "Ecuador", cod_department: 999, cod_municipality: nil},
  {name: "Egipto", cod_department: 999, cod_municipality: nil},
  {name: "El Salvador", cod_department: 999, cod_municipality: nil},
  {name: "Emiratos Arabes Unidos", cod_department: 999, cod_municipality: nil},
  {name: "España", cod_department: 999, cod_municipality: nil},
  {name: "Estados Unidos", cod_department: 999, cod_municipality: nil},
  {name: "Republica De Filipinas", cod_department: 999, cod_municipality: nil},
  {name: "Finlandia", cod_department: 999, cod_municipality: nil},
  {name: "Francia", cod_department: 999, cod_municipality: nil},
  {name: "Grecia", cod_department: 999, cod_municipality: nil},
  {name: "Guatemala", cod_department: 999, cod_municipality: nil},
  {name: "Belice", cod_department: 999, cod_municipality: nil},
  {name: "Paises Bajos", cod_department: 999, cod_municipality: nil},
  {name: "Honduras", cod_department: 999, cod_municipality: nil},
  {name: "India", cod_department: 999, cod_municipality: nil},
  {name: "Indonesia", cod_department: 999, cod_municipality: nil},
  {name: "Inglaterra", cod_department: 999, cod_municipality: nil},
  {name: "Irlanda", cod_department: 999, cod_municipality: nil},
  {name: "Israel", cod_department: 999, cod_municipality: nil},
  {name: "Italia", cod_department: 999, cod_municipality: nil},
  {name: "Jamaica", cod_department: 999, cod_municipality: nil},
  {name: "Japon", cod_department: 999, cod_municipality: nil},
  {name: "Kenia", cod_department: 999, cod_municipality: nil},
  {name: "Luxemburgo", cod_department: 999, cod_municipality: nil},
  {name: "Malasia", cod_department: 999, cod_municipality: nil},
  {name: "Marruecos", cod_department: 999, cod_municipality: nil},
  {name: "Mexico", cod_department: 999, cod_municipality: nil},
  {name: "Nicaragua", cod_department: 999, cod_municipality: nil},
  {name: "Nueva Zelandia", cod_department: 999, cod_municipality: nil},
  {name: "Noruega", cod_department: 999, cod_municipality: nil},
  {name: "Panama", cod_department: 999, cod_municipality: nil},
  {name: "Paraguay", cod_department: 999, cod_municipality: nil},
  {name: "Peru", cod_department: 999, cod_municipality: nil},
  {name: "Polonia", cod_department: 999, cod_municipality: nil},
  {name: "Portugal", cod_department: 999, cod_municipality: nil},
  {name: "Republica Dominicana", cod_department: 999, cod_municipality: nil},
  {name: "Republica De Singapur", cod_department: 999, cod_municipality: nil},
  {name: "Republica Socialista Devietnam", cod_department: 999, cod_municipality: nil},
  {name: "Rusia", cod_department: 999, cod_municipality: nil},
  {name: "Sudafrica", cod_department: 999, cod_municipality: nil},
  {name: "Suecia", cod_department: 999, cod_municipality: nil},
  {name: "Suiza", cod_department: 999, cod_municipality: nil},
  {name: "Tailandia", cod_department: 999, cod_municipality: nil},
  {name: "Turquia", cod_department: 999, cod_municipality: nil},
  {name: "Trinidad Y Tobago", cod_department: 999, cod_municipality: nil},
  {name: "Uruguay", cod_department: 999, cod_municipality: nil},
  {name: "Venezuela", cod_department: 999, cod_municipality: nil}]

municipalities.each do | municipality |
  Department.find_by(cod_department: municipality[:cod_department]).municipalities.create(name: municipality[:name], cod_department: municipality[:cod_department], cod_municipality: municipality[:cod_municipality])
end
User.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?